[package]
name = "cosmos-raiders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.1"
bevy-tokio-tasks = "0.11.0"
bevy_framepace = "0.13.3"
bevy_rapier2d = { version = "0.22.0", features = ["parallel", "debug-render-2d", "wasm-bindgen"] }
bevy_screen_diagnostics = "0.3.0"
bevy_screen_diags = "0.6.0"
hardlight = "2.0.0"
